source 'http://rubygems.org'
gem 'bundler'
gem 'data_mapper'
gem 'dm-core'
gem 'dm-migrations'
gem 'dm-postgres-adapter', '~> 1.2.0'
gem 'sinatra'
gem 'mail'
gem 'prawn', '~> 1.2.1'
gem 'prawn-table', '~> 0.2.0'
gem 'pg'
gem 'aws-s3'
gem 'rack-flash3'